apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmup-engine.fullname" . }}
  labels:
    {{- include "helmup-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    {{- include "helmup-engine.selectorLabels" . | nindent 4 }}
