apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmup-notifications-service.fullname" . }}
  labels:
    {{- include "helmup-notifications-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
  selector:
    {{- include "helmup-notifications-service.selectorLabels" . | nindent 4 }}
