from typing import Tuple
import re
from shared_packages.sirrend_logger import SirrendLogger

logger = SirrendLogger.configure_logger()


class TitleHandler:

    @classmethod
    def validate_sirrend_pr(cls, title: str) -> bool:
        """
        Checks weather a PR was generated by Sirrend.
        :param (str) title: the title to analyze
        :return: (bool) - True is generated by Sirrend, False otherwise
        """
        pattern = r'sirrend/[^/]+/[0-9.]+'
        title = title.lower()

        return bool(re.match(pattern, title))

    @classmethod
    def pr_title_data_extract(cls, title: str) -> Tuple[str, str]:
        """
        Extracts needed attributes from a given PR title.
        Title form: `sirrend/<chart-name>/<new-version>`

        :param (str) title: the title to extract data from.
        :return: Tuple[str, str] - 1st variable is the chart name, 2nd is the new chart version.
        """
        if not cls.validate_sirrend_pr(title):
            logger.warning(f"The PR with the title `{title}` was not created by Sirrend.")
            return "", ""

        _, chart_name, chart_version = title.split("/", 2)
        logger.info(f"PR Title extracted parameters: {{Chart Name: {chart_name}, Version: {chart_version}}}")
        return chart_name, chart_version
