replicaCount: 1

image:
  repository: sirrend/helmup-engine
  pullPolicy: IfNotPresent.
  tag: "0.1.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  enabled: true
  path: /healthcheck
  port: 8090
  initialDelaySeconds: 15
  periodSeconds: 300
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: false
  path: /healthcheck
  port: 8090
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

startupProbe:
  enabled: true
  path: /healthcheck
  port: 8090
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

externalSecret:
  enabled: true
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  backendType: secretsManager  # e.g., secretsManager for AWS Secrets Manager
  secretKeyOpenAI: chatgpt-yuval-token # The secret name to pull from SecretStore for the openAI chatgpt token
  secretKeyGithub: sirrend-github-token
  secretKeyJira: ""
  refreshInterval: 30h
  secretVersion: "" # Optional
  secretTemplate:
    type: Opaque
    annotations: {}
    labels: {}
    data: {}
